[package]
name = "tikv"
version = "3.0.0-beta.1"
authors = ["The TiKV Authors"]
description = "A distributed transactional key-value database powered by Rust and Raft"
license = "Apache-2.0"
keywords = ["KV", "distributed-systems", "raft"]
homepage = "https://tikv.org"
repository = "https://github.com/tikv/tikv/"
readme = "README.md"
edition = "2018"
publish = false

[features]
default = ["tikv_alloc/default"]
tcmalloc = ["tikv_alloc/tcmalloc"]
jemalloc = ["tikv_alloc/jemalloc"]
portable = ["engine/portable"]
sse = ["engine/sse"]
mem-profiling = ["tikv_alloc/mem-profiling"]
profiling = ["profiler/profiling"]
no-fail = ["fail/no_fail"]

[lib]
name = "tikv"

[[bin]]
name = "tikv-server"

[[bin]]
name = "tikv-ctl"

[[bin]]
name = "tikv-importer"

[[test]]
name = "failpoints"
path = "tests/failpoints/mod.rs"

[[test]]
name = "integrations"
path = "tests/integrations/mod.rs"

[[bench]]
name = "raftstore"
harness = false
path = "benches/raftstore/mod.rs"

[[bench]]
name = "coprocessor_executors"
harness = false
path = "benches/coprocessor_executors/mod.rs"

[[bench]]
name = "hierarchy"
harness = false
path = "benches/hierarchy/mod.rs"

[[bench]]
name = "misc"
path = "benches/misc/mod.rs"

[dependencies]
hashbrown = { version = "0.1", features = ["serde"] }
log = { version = "0.3", features = ["max_level_trace", "release_max_level_debug"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = { version = "2.3", default-features = false }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
slog-term = "2.4"
slog_derive = "0.1"
byteorder = "1.2"
rand = "0.6.5"
rand_xorshift = "0.1.1"
quick-error = "1.2.2"
tempdir = "0.3"
time = "0.1"
toml = "0.4"
libc = "0.2"
crc = "1.8"
fs2 = "0.4"
protobuf = "~2.0"
nix = "0.11"
utime = "0.2"
chrono = "0.4"
chrono-tz = "0.5.1"
lazy_static = "0.2.1"
backtrace = "0.2.3"
clap = "2.32"
url = "1.7.2"
regex = "1.0"
sys-info = "0.5.1"
indexmap = { version = "1.0", features = ["serde-1"] }
futures = "0.1"
futures-cpupool = "0.1"
tikv_alloc = { path = "components/tikv_alloc", default-features = false }
tokio-core = "0.1"
tokio-timer = "0.2"
tokio-executor = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
zipf = "5.0.1"
bitflags = "1.0.1"
fail = "0.2"
uuid = { version = "0.6", features = [ "serde", "v4" ] }
grpcio = { version = "0.4", features = [ "secure" ] }
raft = "0.4"
crossbeam = "0.5"
derive_more = "0.11.0"
num = { version = "0.2", default-features = false }
num-traits = "0.2"
hex = "0.3"
rust-crypto = "^0.2"
base64 = "0.10"
safemem = { version = "0.3", default-features = false }
smallvec = { version = "0.6", features = ["union"] }
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
more-asserts = "0.1"
hyper = { version = "0.12", default-features = false, features = ["runtime"] }
tokio-threadpool = "0.1.13"
vlog = "0.1.4"
twoway = "0.2.0"
ordered-float = "1.0"
typed-arena = "1.4.1"
rental = "0.5.3"
profiler = { path = "components/profiler" }
match_template = { path = "components/match_template" }
cop_datatype = { path = "components/cop_datatype" }
cop_codegen = { path = "components/cop_codegen" }
tipb_helper = { path = "components/tipb_helper" }
tipb = { git = "https://github.com/pingcap/tipb.git" }
# TODO: use master branch after the next version is released.
kvproto = { git = "https://github.com/pingcap/kvproto.git", branch = "release-3.0" }
log_wrappers = { path = "components/log_wrappers" }
engine = { path = "components/engine" }
tikv_util = { path = "components/tikv_util" }

[dependencies.murmur3]
git = "https://github.com/pingcap/murmur3.git"

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["nightly", "push", "process"]

[dependencies.prometheus-static-metric]
version = "0.1.4"
default-features = false

# TODO: remove this when slog is compatible with the log 0.4
[replace]
"log:0.3.9" = { git = "https://github.com/busyjay/log", branch = "use-static-module" }
"log:0.4.6" = { git = "https://github.com/busyjay/log", branch = "revert-to-static" }

[dev-dependencies]
panic_hook = { path = "components/panic_hook" }
test_util = { path = "components/test_util" }
test_raftstore = { path = "components/test_raftstore" }
test_storage = { path = "components/test_storage" }
test_coprocessor = { path = "components/test_coprocessor" }
# See https://bheisler.github.io/criterion.rs/book/user_guide/known_limitations.html for the usage
# of `real_blackbox` feature.
criterion = { version = "0.2.11", features=['real_blackbox'] }
arrow = "0.10.0"

[target.'cfg(unix)'.dependencies]
signal = "0.6"

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/tikv/procinfo-rs" }

[workspace]
members = [
  "fuzz",
  "fuzz/fuzzer-afl",
  "fuzz/fuzzer-libfuzzer",
  "fuzz/fuzzer-honggfuzz",
  "components/test_raftstore",
  "components/test_storage",
  "components/test_coprocessor",
  "components/test_util",
  "components/tikv_alloc",
  "components/match_template",
  "components/codec",
  "components/panic_hook",
  "components/cop_datatype",
  "components/cop_codegen",
  "components/tipb_helper",
  "components/log_wrappers",
  "components/tikv_util",
]

[profile.dev]
opt-level = 0  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`
codegen-units = 4
panic = 'abort'

# The release profile, used for `cargo build --release`
[profile.release]
lto = true
opt-level = 3
debug = true
# TODO: remove this once rust-lang/rust#50199 and rust-lang/rust#53833 are resolved.
codegen-units = 1
panic = 'abort'

# The benchmark profile is identical to release, except that lto = false
[profile.bench]
lto = false
opt-level = 3
debug = true
codegen-units = 1
